### ISSUE TITLE
No method named `percent`, `precent_left` found for struct `bevy::prelude::Timer`

### ISSUE THREAD

**Issue by kalin-p** [vleue/bevy_easings#30]
This crate was added as a dependency to `bevy_panorbit_camera`, but fails compilation with the message in the title. I am using bevy 0.12.0, bevy_easings 0.12.2.

**Comment by mockersf** [comment]
Could you give the complete error message with context, or link to a project that fails to compile? I can't reproduce your issue, `bevy_panorbit_camera` compiles correctly for me.

**Comment by kalin-p** [comment]
I will try to reproduce the issue, yesterday while I was trying to go around it I ran into some bevy problems, so it might be a while. If you'd like you can close the issue for now, as soon as I have more info I'll post an update.
